@baseurl=https://tasks-3luj.onrender.com
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6Ik5hbmRoYSIsImlhdCI6MTczNDMzNjU3MiwiZXhwIjoxNzM0NDIyOTcyfQ.yuTnb50mp8-ZelWsK5tsZOar14_xCgBlO2304r58apM

### Register User Account
POST https://tasks-3luj.onrender.com/auth/register
Content-Type: application/json

{
  "name": "Nandha",
  "email": "Nandha@example.com",
  "password": "password123"
}
### Login User 
POST https://tasks-3luj.onrender.com/auth/login
Content-Type: application/json

{
  "email": "Nandha@example.com",
  "password": "password123"
}

###Logout user
POST {{baseurl}}/auth/logout
Authorization: Bearer {{token}}
Content-Type: application/json

###Get all tasks
GET {{baseurl}}/todos
Authorization: Bearer {{token}}

### Create a TODO
POST {{baseurl}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "work project",
  "start_time": "2024-12-14T11:00:00Z",
  "end_time": "2024-12-14T21:00:00Z",
  "priority": 5,
  "status": "pending"
}

### Update a TODO
PUT {{baseurl}}/todos/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "completed project",
  "start_time": "2024-12-16T10:00:00Z",
  "end_time": "2024-12-17T12:00:00Z",
  "priority": 2,
  "status": "finished"
}

### Delete a TODO
DELETE {{baseurl}}/todos/1
Authorization: Bearer {{token}}



